######################################################################
# Automatically generated by qmake (2.01a) jeu. nov. 24 22:48:06 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Histogram.h ImageViewer.h ImgDescription.h SearchDialog.h
SOURCES += Histogram.cpp \
           ImageViewer.cpp \
           ImgDescription.cpp \
           main.cpp \
           SearchDialog.cpp
